jQuery.noConflict();

const translations = {
  en: {
    home: "Home",
    about: "About",
    process: "Process",
    projects: "Projects",
    contact: "Contact",
    portfolio: "Portfolio",
    about1: "About Me",
    about2: "My name is Marcos Vinicius Martins de Lima, and I help companies to solve their problems through design, always with business vision, strategic focus and guided by data.",
    about3: "I have more than 6 years of experience in the UX/UI Design field, and more than 15 years as Web Designer.",
    about4: "I led Design System projects and assisted in the development of new apps, websites and features working with product and development teams.",
    skills: "My Skills",
    responsive: "Responsive Design",
    adaptable: "Adaptable Design",
    prototype: "Prototype",
    accessibility: "Accessibility",
    resume: "Resume",
    process1: "My Design Process",
    process2: "I like to understand first and create after. Those are the steps that guide my work from start to finish.",
    process3: "Empathize",
    process3desc: "Understand the user's needs, pain points, and motivations.",
    process4: "Define",
    process4desc: "Clearly articulate the problem statement based on user insights.",
    process5: "Ideate",
    process5desc: "Generate a wide range of ideas to address the defined problem.",
    process6: "Prototype",
    process6desc: "Build interactive, digital wireframes or mid-to-high fidelity prototypes to validate design and usability.",
    process7: "Test",
    process7desc: "Put prototypes in front of real users to watch how they interact, spot pain points, and gather direct feedback.",
    process8: "Iterate",
    process8desc: "Refine and re-test the product based on user findings before finalizing the design for developer handoff.",
    projects1: "My Projects",
    projects2: "Take a look at my portfolio and see how my experience can help your team.",
    project1desc: "An app to book a car from the fleet from Grupo NotreDame Intermédica, where you can choose a car, schedule a day for use and verify the vehicle details.",
    project2desc: "An app to book rooms or individual spaces for Coworkings, where you can choose by region, select room details, book and pay for it.",
    project3desc: "An easy way to alocate our employees when they need to come to the office, so they can book meeting rooms or working station respecting social distances.",
    project4desc: "Our field workers need and app to help them with their appointments, to know when and where it is and what to do there.",
    project5desc: "An app to create, draw and prepare a secret santa, with a way to get more information about the person you pick and their wanted gifts.",
    project6desc: "Redesign the MobyPharma app, used for request and payment for medicine, directly with the pharmacy of your choice, with integrated chat, multiple payment methods and news about the branch of business.",
    project7desc: "Redesign the layout for the ERP PharmaPhusion, a management system for compounding pharmacies.",
    project8desc: "An institutional website layout for a new learning platform.",
    project9desc: "Redesign the layout for the Entouch Controls Portal for management of HVAC and refrigeration systems.",
    seeproject: "See Project",
    contacts1: "My Contacts",
    contacts2: "Reach out and lets talk.",
    projectname: "Project Name",
    company: "Company",
    problem: "Problem",
    maingoal: "Main Goal",
    research: "Research",
    userinterviews: "User Interviews",
    competitoranalysis: "Competitor Analysis",
    designprocess: "Design Process",
    userflow: "User Flowchart",
    prototype: "Prototype",
    otherprojects: "Other Projects",
    backtotop: "Back to Top",
    gndi1: "We need an app to book a car from the fleet from Grupo NotreDame Intermédica, where you can choose a car, schedule a day for use and verify the vehicle details.",
    gndi2: "Too much paper to handle the car lending;",
    gndi3: "Lots of damages to the vehicle not registered;",
    gndi4: "Troubles with the schedule, car booked for 2 people at the same time.",
    gndi5: "Assist the company to easier manage their fleet used to visit clients.",
    gndi6: "They want and easy way to schedule the days to use a car;",
    gndi7: "A simple and efficient way to show the condition of the vehicle (damages and fuel);",
    gndi8: "Make a check-out and a check-in.",
    gndi9: "Simple forms to fill in to book a car;",
    gndi10: "Damage reports still on paper.",
    gndi11: "Interview users and stakeholders;",
    gndi12: "Reseach the competitors;",
    gndi13: "Build user flowchart;",
    gndi14: "Design prototype.",
    coworking1: "Need an app to book rooms or individual spaces for Coworkings, where you can choose by region, select room details, book and pay for it.",
    coworking2: "It is hard to find a place to work remotely;",
    coworking3: "Not so much information about the place you want to book;",
    coworking4: "Difficulty to make a payment.",
    coworking5: "Allow an easier way to book a place on a coworking space.",
    coworking6: "Need to have a good filter to find a place that fits;",
    coworking7: "A way to choose what you need for your work;",
    coworking8: "Remember when and where the place is booked.",
    coworking9: "It is really hard to talk to the responsible person for the space;",
    coworking10: "Easy to schedule a day and find a place.",
    coworking11: "Interview users and stakeholders;",
    coworking12: "Research the competitors;",
    coworking13: "Build user flowchart;",
    coworking14: "Design prototype.",
    invitee1: "We need an easy way to alocate our employees when they need to come to the office, so they can book meeting rooms or working station respecting social distances.",
    invitee2: "It is hard to alocate everyone working on-site;",
    invitee3: "Need to keep social distancing.",
    invitee4: "Allow the employees to book stations when working on-site.",
    invitee5: "Need a safe spot to work when going on-site;",
    invitee6: "Have to know if there is everything I need to work;",
    invitee7: "An easy way to book a spot.",
    invitee8: "Don't show a map of the office to knowwhere is the spot you'll choose;",
    invitee9: "Easy to navigate, clean.",
    invitee10: "Interview users and stakeholders;",
    invitee11: "Research the competitors;",
    invitee12: "Build user flowchart;",
    invitee13: "Design prototype.",
    fieldservice1: "Our field workers need and app to help them with their appointments, to know when and where it is and what to do there.",
    fieldservice2: "Today, everything is on paper, and they want to reduce it;",
    fieldservice3: "Hard to keep track of what is needed to bring, so they bring all the tools;",
    fieldservice4: "Need a more practical way to manage their schedule.",
    fieldservice5: "Make the working process easier for field service workers.",
    fieldservice6: "They don't want to use paper (not even to collect a signature);",
    fieldservice7: "Easy way to know where, when and with who they will work with;",
    fieldservice8: "Notify of every completed step.",
    fieldservice9: "Interview users and stakeholders;",
    fieldservice10: "Build user flowchart;",
    fieldservice11: "Design prototype.",
    amigo1: "Make an app to create, draw and prepare a secret santa, with a way to get more information about the person you pick and their wanted gifts.",
    amigo2: "Needs to be able to create several events;",
    amigo3: "Find a way to make a gamification to get more information;",
    amigo4: "Be able to increase the possibility to draw an specific person.",
    amigo5: "Create a secret santa drawing app.",
    amigo6: "Looks to messy and hard to navigate;",
    amigo7: "Has several ads (free version);",
    amigo8: "Can only create an event with a limited number of people.",
    amigo9: "Research the competitors;",
    amigo10: "Build user flowchart;",
    amigo11: "Design prototype.",
    mobypharma1: "Redesign the MobyPharma app, used for request and payment for medicine, directly with the pharmacy of your choice, with integrated chat, multiple payment methods and news about the branch of business.",
    mobypharma2: "The layout is already too old;",
    mobypharma3: "Some parts are hard to navigate and understand.",
    mobypharma4: "Make a cleaner layout and easy to navigate so the process can be faster.",
    mobypharma5: "The app is to messy and looks really outdated;",
    mobypharma6: "Not many payment methods;",
    mobypharma7: "It is not updated frequently.",
    mobypharma8: "They have a fresher look, but not so many features;",
    mobypharma9: "Have easier payment methods.",
    mobypharma10: "Interview users and stakeholders;",
    mobypharma11: "Research the competitors;",
    mobypharma12: "Build user flowchart;",
    mobypharma13: "Design prototype.",
    phusion1: "Redesign the layout for the ERP PharmaPhusion, a management system for compounding pharmacies.",
    phusion2: "The layout is outdated and there is only a light mode;",
    phusion3: "Many pharmacies are already used to it.",
    phusion4: "Modernize the layout for the system and implement a dark mode.",
    phusion5: "The layout looks cleaner and modern;",
    phusion6: "There are other things to solve before doing a redesign.",
    phusion7: "Smaller side menus and overall fonts;",
    phusion8: "More information on screen without looking to clustered;",
    phusion9: "Always has a light and a dark mode.",
    phusion10: "Interview users and stakeholders;",
    phusion11: "Research the competitors;",
    phusion12: "Design prototype.",
    learningbits1: "Make an institutional website layout for a new learning platform.",
    learningbits2: "Needs to bring attention from the public.",
    learningbits3: "Make a layout that stands out among the many learning platforms.",
    learningbits4: "Always show the pricing and has a free option;",
    learningbits5: "Easy to start and find the courses you want.",
    learningbits6: "Research the competitors;",
    learningbits7: "Design prototype.",
    entouch1: "Redesign the layout for the Entouch Controls Portal for management of HVAC and refrigeration systems.",
    entouch2: "The layout is outdated and needs lots of training to be able to work well with it;",
    entouch3: "Lots of clients use only a part of the system, not the whole.",
    entouch4: "Modernize the layout for the system and make it easier to find the information the client needs.",
    entouch5: "We need and easier system, it is too hard to find some things we need and takes lots of steps;",
    entouch6: "The look is really outdated, maybe do something more modern;",
    entouch7: "Some parts of the system need a better highlight, like the temperature widget.",
    entouch8: "Modern look and easier usability;",
    entouch9: "It is simple to access the important parts of the system.",
    entouch10: "Interview users and stakeholders;",
    entouch11: "Research the competitors;",
    entouch12: "Review user flowchart;",
    entouch13: "Review pages needed in the system;",
    entouch14: "Design wireframes;",
    entouch15: "Design prototype."
  },
  pt: {
    home: "Início",
    about: "Sobre",
    process: "Processo",
    projects: "Projetos",
    contact: "Contato",
    portfolio: "Portfólio",
    about1: "Sobre Mim",
    about2: "Meu nome é Marcos Vinicius Martins de Lima, e ajudo empresas a resolver seus problemas por meio do design, sempre com visão de negócio, foco estratégico e orientado por dados.",
    about3: "Tenho mais de 6 anos de experiência no campo de UX/UI Design, e mais de 15 anos como Web Designer.",
    about4: "Liderei projetos de Design System e auxiliei no desenvolvimento de novos aplicativos, sites e recursos trabalhando com equipes de produto e desenvolvimento.",
    skills: "Minhas Habilidades",
    responsive: "Design Responsivo",
    adaptable: "Design Adaptável",
    prototype: "Protótipo",
    accessibility: "Acessibilidade",
    resume: "Currículo",
    process1: "Meu Processo de Design",
    process2: "Gosto de entender primeiro e criar depois. Esses são os passos que guiam meu trabalho do início ao fim.",
    process3: "Identificar",
    process3desc: "Entender as necessidades, pontos de dor e motivações do usuário.",
    process4: "Definir",
    process4desc: "Discutir a raiz do problema com base nas descobertas do usuário.",
    process5: "Idealizar",
    process5desc: "Gerar uma ampla gama de ideias para abordar o problema definido.",
    process6: "Prototipar",
    process6desc: "Construir wireframes digitais interativos ou protótipos de média a alta fidelidade para validar design e usabilidade.",
    process7: "Testar",
    process7desc: "Colocar protótipos diante de usuários reais para observar como eles interagem, identificar pontos de dor e coletar feedback direto.",
    process8: "Repetir",
    process8desc: "Refinar e testar novamente o produto com base nas descobertas dos usuários antes de finalizar o design para passar ao desenvolvedor.",
    projects1: "Meus Projetos",
    projects2: "Dê uma olhada em meu portfólio e veja como minha experiência pode ajudar sua equipe.",
    project1desc: "Um aplicativo para reservar um carro da frota do Grupo NotreDame Intermédica, onde você pode escolher um carro, agendar um dia de uso e verificar os detalhes do veículo.",
    project2desc: "Um aplicativo para reservar salas ou espaços individuais para Coworkings, onde você pode escolher por região, selecionar detalhes da sala, reservar e pagar por ela.",
    project3desc: "Uma maneira fácil de alocar nossos funcionários quando eles precisam vir ao escritório, para que possam reservar salas de reunião ou estações de trabalho respeitando o distanciamento social.",
    project4desc: "Nossos trabalhadores de campo precisam de um aplicativo para ajudá-los com seus compromissos, para saber quando e onde é e o que fazer lá.",
    project5desc: "Um aplicativo para criar, sortear e preparar um amigo secreto, com uma maneira de obter mais informações sobre a pessoa que você escolheu e seus presentes desejados.",
    project6desc: "Redesenhar o aplicativo MobyPharma, usado para solicitação e pagamento de medicamentos, diretamente com a farmácia de sua escolha, com chat integrado, múltiplos métodos de pagamento e notícias sobre o ramo de negócios.",
    project7desc: "Redesenhar o layout do ERP PharmaPhusion, um sistema de gestão para farmácias de manipulação.",
    project8desc: "Um layout de site institucional para uma nova plataforma de aprendizado.",
    project9desc: "Redesenhar o layout do Portal Entouch Controls para gerenciamento de sistemas de HVAC e refrigeração.",
    seeproject: "Ver Projeto",
    contacts1: "Meus Contatos",
    contacts2: "Entre em contato e vamos conversar.",
    projectname: "Nome do Projeto",
    company: "Empresa",
    problem: "Problema",
    maingoal: "Objetivo Principal",
    research: "Pesquisa",
    userinterviews: "Entrevistas com Usuários",
    competitoranalysis: "Análise de Concorrentes",
    designprocess: "Processo de Design",
    userflow: "Fluxograma do Usuário",
    prototype: "Protótipo",
    otherprojects: "Outros Projetos",
    backtotop: "Voltar ao Topo",
    gndi1: "Precisamos de um aplicativo para reservar um carro da frota do Grupo NotreDame Intermédica, onde você pode escolher um carro, agendar um dia de uso e verificar os detalhes do veículo.",
    gndi2: "Muita papelada para lidar com o empréstimo de carros;",
    gndi3: "Muitos danos não registrados ao veículo;",
    gndi4: "Problemas com o agendamento, carro reservado para 2 pessoas ao mesmo tempo.",
    gndi5: "Auxiliar a empresa a gerenciar mais facilmente sua frota usada para visitar clientes.",
    gndi6: "Eles querem uma maneira fácil de agendar os dias para usar um carro;",
    gndi7: "Uma maneira simples e eficiente de mostrar a condição do veículo (danos e combustível);",
    gndi8: "Fazer um check-out e um check-in.",
    gndi9: "Formulários simples para preencher ao reservar um carro;",
    gndi10: "Relatórios de danos ainda em papel.",
    gndi11: "Entrevistas com usuários e stakeholders;",
    gndi12: "Pesquisa dos concorrentes;",
    gndi13: "Criação do fluxo do usuário;",
    gndi14: "Design do protótipo.",
    coworking1: "Precisamos de um aplicativo para reservar salas ou espaços individuais para Coworkings, onde você pode escolher por região, selecionar detalhes da sala, reservar e pagar por ela.",
    coworking2: "É difícil encontrar um lugar para trabalhar remotamente;",
    coworking3: "Poucas informações sobre o local que você deseja reservar;",
    coworking4: "Dificuldade para fazer o pagamento.",
    coworking5: "Permitir uma forma mais fácil de reservar um lugar em um espaço de coworking.",
    coworking6: "Precisa ter um bom filtro para encontrar um lugar que se adeque;",
    coworking7: "Uma forma de escolher o que você precisa para o seu trabalho;",
    coworking8: "Lembrar quando e onde o lugar está reservado.",
    coworking9: "É realmente difícil conversar com a pessoa responsável pelo espaço;",
    coworking10: "Fácil de agendar um dia e encontrar um lugar.",
    coworking11: "Entrevistas com usuários e stakeholders;",
    coworking12: "Pesquisa dos concorrentes;",
    coworking13: "Criação do fluxo do usuário;",
    coworking14: "Design do protótipo.",
    invitee1: "Precisamos de um aplicativo que permita alocar nossos funcionários quando eles precisarem vir ao escritório, para que possam agendar salas de reunião ou estações de trabalho respeitando as distâncias sociais.",
    invitee2: "É difícil alocar todos os funcionários que trabalham no local;",
    invitee3: "Precisamos manter o distanciamento social.",
    invitee4: "Permitir que os funcionários reservem espaços quando trabalhando no local.",
    invitee5: "Precisamos de um local seguro para trabalhar quando formos ao escritório;",
    invitee6: "Precisamos saber se tem tudo o que preciso para trabalhar;",
    invitee7: "Uma maneira fácil de agendar um lugar.",
    invitee8: "Não mostra um mapa do escritório para saber onde está o lugar que você vai escolher;",
    invitee9: "Fácil de navegar, limpo.",
    invitee10: "Entrevistas com usuários e stakeholders;",
    invitee11: "Pesquisa dos concorrentes;",
    invitee12: "Criação do fluxo do usuário;",
    invitee13: "Design do protótipo.",
    fieldservice1: "Nossos trabalhadores de campo precisam de um aplicativo para ajudá-los com seus compromissos, para saber quando e onde é e o que fazer lá.",
    fieldservice2: "Hoje, tudo está em papel, e eles querem reduzir isso;",
    fieldservice3: "Difícil acompanhar o que é necessário trazer, então eles trazem todas as ferramentas;",
    fieldservice4: "Precisamos de uma forma mais prática para gerenciar seu cronograma.",
    fieldservice5: "Tornar o processo de trabalho mais fácil para os trabalhadores de campo.",
    fieldservice6: "Eles não querem usar papel (nem mesmo para coletar uma assinatura);",
    fieldservice7: "Forma fácil de saber onde, quando e com quem eles vão trabalhar;",
    fieldservice8: "Notificação de cada etapa concluída.",
    fieldservice9: "Entrevistas com usuários e stakeholders;",
    fieldservice10: "Criação do fluxo do usuário;",
    fieldservice11: "Design do protótipo.",
    amigo1: "Fazer um aplicativo para criar, sortear e preparar um amigo secreto, com uma maneira de obter mais informações sobre a pessoa que você escolheu e seus presentes desejados.",
    amigo2: "Precisa ser capaz de criar vários eventos;",
    amigo3: "Encontrar uma maneira de fazer uma gamificação para obter mais informações;",
    amigo4: "Ser capaz de aumentar a possibilidade de sortear uma pessoa específica.",
    amigo5: "Criar um aplicativo de sorteio de amigo secreto.",
    amigo6: "Parece bagunçado e difícil de navegar;",
    amigo7: "Tem vários anúncios (versão gratuita);",
    amigo8: "Só pode criar um evento com um número limitado de pessoas.",
    amigo9: "Pesquisar os concorrentes;",
    amigo10: "Construir o fluxo do usuário;",
    amigo11: "Design do protótipo.",
    mobypharma1: "Redesenhar o aplicativo MobyPharma, usado para solicitação e pagamento de medicamentos, diretamente com a farmácia de sua escolha, com chat integrado, múltiplos métodos de pagamento e notícias sobre o ramo de negócios.",
    mobypharma2: "O layout já está muito antigo;",
    mobypharma3: "Algumas partes são difíceis de navegar e entender.",
    mobypharma4: "Fazer um layout mais limpo e fácil de navegar para que o processo seja mais rápido.",
    mobypharma5: "O aplicativo está bagunçado e parece muito desatualizado;",
    mobypharma6: "Não há muitos métodos de pagamento disponíveis;",
    mobypharma7: "O aplicativo não é atualizado com frequência.",
    mobypharma8: "Eles têm um visual mais novo, mas não tão muitas funcionalidades;",
    mobypharma9: "Têm métodos de pagamento mais fáceis de usar.",
    mobypharma10: "Entrevistar usuários e stakeholders;",
    mobypharma11: "Pesquisar os concorrentes;",
    mobypharma12: "Construir o fluxo do usuário;",
    mobypharma13: "Design do protótipo.",
    phusion1: "Redesenhar o layout do ERP PharmaPhusion, um sistema de gestão para farmácias de manipulação.",
    phusion2: "O layout está desatualizado e só existe um modo claro;",
    phusion3: "Muitas farmácias já estão acostumadas com ele.",
    phusion4: "Modernizar o layout do sistema e implementar um modo escuro.",
    phusion5: "O layout parece mais limpo e moderno;",
    phusion6: "Existem outras coisas a serem resolvidas antes de fazer um redesenho.",
    phusion7: "Menus laterais e fontes globais menores;",
    phusion8: "Mais informações na tela sem parecer entulhada;",
    phusion9: "Sempre tem um modo claro e um modo escuro.",
    phusion10: "Entrevistar usuários e stakeholders;",
    phusion11: "Pesquisar os concorrentes;",
    phusion12: "Design do protótipo.",
    learningbits1: "Fazer um layout de site institucional para uma nova plataforma de aprendizado.",
    learningbits2: "Precisa chamar atenção do público.",
    learningbits3: "Fazer um layout que se destaque entre as muitas plataformas de aprendizado.",
    learningbits4: "Sempre mostrar os preços e ter uma opção gratuita;",
    learningbits5: "Fácil de começar e encontrar os cursos que você deseja.",
    learningbits6: "Pesquisar os concorrentes;",
    learningbits7: "Design do protótipo.",
    entouch1: "Redesenhar o layout do Portal Entouch Controls para gerenciamento de sistemas de HVAC e refrigeração.",
    entouch2: "O layout está desatualizado e precisa de muito treinamento para conseguir trabalhar bem com ele;",
    entouch3: "Muitos clientes usam apenas uma parte do sistema, não o todo.",
    entouch4: "Modernizar o layout do sistema e torná-lo mais fácil de encontrar as informações que o cliente precisa.",
    entouch5: "Precisamos de um sistema mais fácil, é muito difícil encontrar algumas coisas que precisamos e isso exige muitas etapas;",
    entouch6: "A aparência está muito desatualizada, talvez possamos fazer algo mais moderno;",
    entouch7: "Algumas partes do sistema precisam de um melhor destaque, como o widget da temperatura.",
    entouch8: "Aparência moderna e usabilidade mais simples;",
    entouch9: "É simples acessar as partes importantes do sistema.",
    entouch10: "Entrevistar usuários e stakeholders;",
    entouch11: "Pesquisar os concorrentes;",
    entouch12: "Revisar o fluxo do usuário;",
    entouch13: "Revisar as páginas necessárias no sistema;",
    entouch14: "Design dos wireframes;",
    entouch15: "Design do protótipo."
  }
};

// Core translation driver function
function translatePage(lang) {
    // Select all elements with the data-i18n attribute
    const elements = document.querySelectorAll("[data-i18n]");
    
    elements.forEach(element => {
        const key = element.getAttribute("data-i18n");
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });

    // Optional: Persist the selection so it remains on page reload
    localStorage.setItem("preferredLanguage", lang);
    document.documentElement.lang = lang; 
}

// Event listener for dropdown menu
document.getElementById("language-toggle").addEventListener("change", (e) => {
    translatePage(e.target.value);
});

// On page load: check cache or fall back to default
window.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("preferredLanguage") || "en";
    document.getElementById("language-toggle").value = savedLang;
    translatePage(savedLang);
});


